services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.gustavocastro.com
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`home.gustavocastro.com`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
    networks:
      - traefik

volumes:
  homepage:
    external: true

networks:
  traefik:
    external: true