services:
  traefik:
    image: traefik:v3.5.1
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - traefik_config:/etc/traefik
      - traefik_dynamic:/dynamic
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  letsencrypt:
  traefik_config:
    external: true
  traefik_dynamic:
    external: true