- Networking:
    - PiHole:
        icon: pi-hole
        href: http://pihole.gustavocastro.com/admin/
        description: PiHole
        widget:
          type: pihole
          url: http://100.108.148.43/
          version: 6
          fields: ["queries", "blocked_percent", "gravity"]
          key: LG0ReyfETfl/lWiKFWSMo3N6alfKwWgyJGhq1Agoz+Y=
#    - Traefik:
#        icon: traefik.png
#        description: traefik
#        href: http://traefik.home/
#        server: local-docker
#        container: traefik-traefik-1
#        widget:
#          type: traefik
#          url: http://traefik.home
- Files:
    - Cloudreve:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/cloudreve.png
        href: https://files.gustavocastro.com/
        description: Files
        showStats: true
        server: local-docker
        container: cloudreve-backend
    - Paperless:
        icon: si-paperlessngx
        href: https://paperless.gustavocastro.com/
        description: Paperless-ngx
        server: local-docker
        container: 	paperless-ngx-webserver-1
        widget:
          type: paperlessngx
          url: https://paperless.gustavocastro.com/
          key: a92f8416e814a0e84892ac3e2803e87ef9f45735
- Apps:
    - Blinko:
        server: local-docker
        container: blinko-website
        showStats: true
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/blinko.png
        description: blinko
        href: https://blinko.gustavocastro.com/
    - Blinko Postgres:
        server: local-docker
        container: blinko-postgres
        showStats: true
        icon: postgresql
        description: blinko database
    - Uptime Kuma:
        icon: uptime-kuma
        href: https://uptime.gustavocastro.com/status/uptime
        description: Uptime monitor
        widget:
          type: uptimekuma
          url: https://uptime.gustavocastro.com/
          slug: uptime
    - Vaultwarden:
        icon: si-bitwarden
        siteMonitor: https://bitwarden.gustavocastro.com
        href: https://bitwarden.gustavocastro.com
        description: Passwords
    - gustavocastro.com:
        icon: mdi-account-circle-outline
        siteMonitor: https://gustavocastro.com
        href: https://gustavocastro.com
        description: nothing to see here
